name: Laravel Linting

on: [push, pull_request] # Menjalankan linting setiap ada push atau PR

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12' # Sesuaikan dengan versi PHP yang digunakan
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 app/
